name: Deploy Storage Container and Databricks Setup

on:
  workflow_dispatch:
    inputs:
      storageAccountName:
        description: 'Storage Account Name'
        required: true
      containerName:
        description: 'Container Name'
        required: true
      resourceGroupName:
        description: 'Resource Group Name'
        required: true
      clientName:
        description: 'Client Name'
        required: true

jobs:
  deploy-and-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate container names
        id: generate_names
        run: |
          BASE_CONTAINERS=("staging" "intermediate" "failed")
          PREFIXED_CONTAINERS=()
          for c in "${BASE_CONTAINERS[@]}"; do
            PREFIXED_CONTAINERS+=("${{ github.event.inputs.clientName }}_${c}")
          done
          echo "containers=$(IFS=,; echo \"${PREFIXED_CONTAINERS[*]}\")" >> $GITHUB_OUTPUT

      - name: Set up Azure CLI
        uses: azure/cli@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Blob Container via ARM Template
        run: |
          IFS=',' read -ra CONTAINERS <<< "${{ steps.generate_names.outputs.containers }}"
          for container in "${CONTAINERS[@]}"; do
            az deployment group create \
              --resource-group ${{ github.event.inputs.resourceGroupName }} \
              --template-file create-container.json \
              --parameters storageAccountName=${{ github.event.inputs.storageAccountName }} containerName=$container
          done

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Databricks Setup Script
        if: ${{ success() }}
        env:
          STORAGE_ACCOUNT: ${{ github.event.inputs.storageAccountName }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          CONTAINERS: ${{ steps.generate_names.outputs.containers }}
        run: |
          python databricks_setup.py --storage-account "$STORAGE_ACCOUNT" --container-names $(echo $CONTAINERS | tr ',' ' ')